plugin:
  # See https://k9scli.io/topics/plugins/
  log-less:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
    - po
    command: bash
    background: false
    args:
    - -c
    - '"$@" | less'
    - dummy-arg
    - kubectl
    - logs
    - $NAME
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
  log-less-container:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
    - containers
    command: bash
    background: false
    args:
    - -c
    - '"$@" | less'
    - dummy-arg
    - kubectl
    - logs
    - -c
    - $NAME
    - $POD
    - -n
    - $NAMESPACE
    - --context
    - $CONTEXT
