# Some useful shortcuts
alias la="ls -altr"
alias -- -="cd -"
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ......="cd ../../../../../"
alias myip="curl ifconfig.me"
alias del="trash"
alias activate-old="source ~/.pyenv/versions/venv/bin/activate"
alias activate="source /Users/andrevauvelle/Library/Caches/pypoetry/virtualenvs/optimal-bid-day-ahead-ASHhx2AB-py3.11/bin/activate"
